import "@mantine/core/styles.css";
import { Inter } from "next/font/google";
import type { ReactNode } from "react";

import { ColorSchemeScript, MantineProvider } from "@mantine/core";
import { theme } from "~/theme";
import { TRPCReactProvider } from "~/trpc/react";

const inter = Inter({
	subsets: ["latin"],
});

export const metadata = {
	title: "TodoAppAI",
	description: "Generated by create-t3-app, Auth0, Vercel, PlanetScale",
	icons: [{ rel: "icon", url: "/favicon.svg" }],
};

export default function RootLayout({
	children,
}: {
	children: ReactNode;
}) {
	return (
		<html lang="en">
			<head>
				<ColorSchemeScript />
			</head>
			<body className={inter.className}>
				<TRPCReactProvider>
					<MantineProvider theme={theme}>{children}</MantineProvider>
				</TRPCReactProvider>
			</body>
		</html>
	);
}
