import { Inter } from "next/font/google";
import type { ReactNode } from "react";
import "~/styles/globals.css";
import { TRPCReactProvider } from "~/trpc/react";

const inter = Inter({
	subsets: ["latin"],
});

export const metadata = {
	title: "TodoAppAI",
	description: "Generated by create-t3-app, Auth0, Vercel, PlanetScale",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
	children,
}: {
	children: ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<TRPCReactProvider>{children}</TRPCReactProvider>
			</body>
		</html>
	);
}
