name: Execute lint, type-check

on:
  workflow_dispatch:
  pull_request:
    branches: [develop]
    paths:
      - "src/**"

jobs:
  lint-and-type-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Intall dependencies
        run: bun install
      - name: Lint
        run: bun lint && bun type:check